name: Build MikaKernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    env:
      KBUILD_BUILD_USER: lynx
      KBUILD_BUILD_HOST: workspace

    steps:
    - uses: actions/checkout@v4

    - name: Get Date & Time
      id: date
      run: |
        echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        echo "time=$(date +'%H:%M:%S')" >> $GITHUB_OUTPUT

    - name: Send Telegram Notification (Build Triggered)
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          üöÄ Build Triggered!
          ‚åõ Estimated Time : ¬±7‚Äì15 mins
          üìÖ Date : ${{ steps.date.outputs.date }}
          üïê Time : ${{ steps.date.outputs.time }}

    - name: Setup environment
      run: |
        echo "ANYKERNEL_SOURCE=$(grep -w "ANYKERNEL_SOURCE" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "ANYKERNEL_SOURCE_BRANCH=$(grep -w "ANYKERNEL_SOURCE_BRANCH" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNEL_SOURCE=$(grep -w "KERNEL_SOURCE" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNEL_SOURCE_BRANCH=$(grep -w "KERNEL_SOURCE_BRANCH" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNEL_CONFIG=$(grep -w "KERNEL_CONFIG" config.env | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "BUILD_ARGS=$(grep -w "BUILD_ARGS" config.env | cut -d ":" -f 2)" >> $GITHUB_ENV

    - name: Pull toolchain
      run: |
        git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64-linux-android-4.9
        git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm-linux-androideabi-4.9
        mkdir clang
        curl -RL https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android14-dev/clang-r487747c.tar.gz -o clang.tar.gz
        tar -C clang/ -xf clang.tar.gz

    - name: Pull kernel source
      run: git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} kernel-source

    - name: Build kernel
      run: |
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        args="ARCH=arm64 \
              O=../out \
              ${{ env.BUILD_ARGS }} \
              CLANG_TRIPLE=aarch64-linux-gnu- \
              CROSS_COMPILE=$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin/aarch64-linux-android- \
              CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-"
        cd kernel-source
        make ${args} ${{ env.KERNEL_CONFIG }}
        make -j$(nproc) ${args}

    - name: Package kernel
      run: |
        git clone --depth=1 ${{ env.ANYKERNEL_SOURCE }} -b ${{ env.ANYKERNEL_SOURCE_BRANCH }} AnyKernel3
        rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
        if [[ -f out/arch/arm64/boot/Image.gz-dtb ]]; then
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
        elif [[ -f out/arch/arm64/boot/Image-dtb ]]; then
          cp out/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
        elif [[ -f out/arch/arm64/boot/Image.gz ]]; then
          cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
        elif [[ -f out/arch/arm64/boot/Image ]]; then
          cp out/arch/arm64/boot/Image AnyKernel3/Image
        fi
        if [[ -f out/arch/arm64/boot/dtbo.img ]]; then
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
        fi

    - name: Upload kernel to artifact
      uses: actions/upload-artifact@v4
      with:
        name: Axira Begonia
        path: AnyKernel3/*

    - name: Send Telegram Notification (Success)
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ‚úÖ Build Success!
          üì¶ Axira Begonia uploaded
          üë§ Built by : ${{ github.actor }}

    - name: Send Telegram Notification (Failed)
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ‚ùå Build Failed!
          üîó Commit : ${{ github.sha }}
          ‚ö†Ô∏è Check Actions tab for error logs
